config/routes.rb
Phew::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "posts/index"
  devise_for :users,  controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tribes do 
    member do
      get 'tribe/:duration', to: 'tribes#show', as: :top
      get 'new/:duration',   to: 'tribes#show', as: :new  
    end
  end

  resources :sub_tribes do
    member do
      get 'sub_tribe/:duration', to: 'sub_tribes#show', as: :top
      get 'new/:duration', to: 'sub_tribes#show', as: :new  
    end
  end
  
  resources :users do
    member do 
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  

  
  resources :posts do 
    member do
      post "upvote", to: "posts#upvote"
      post "downvote", to: "posts#downvote"
      delete "delete", to: "posts#delete"
      post 'report', to: 'posts#report_post'
    end
    resources :comments do
      member do 
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote" 
        delete "delete", to: "comments#delete"
        post "report", to: 'comments#report_comment'
      end
    end
  end
  root  to: 'posts#index'

  match '/posts/new', to: 'posts#new', via: 'get'

  post 'add_comment', to: 'posts#add_comment'
  post 'add_child_comment', to: 'posts#add_child_comment'
  
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'top/:duration', to: 'posts#index', as: :top
  get 'new/:duration', to: 'posts#index', as: :new
  get 'search', to: 'posts#search'
  
  post 'add_post_directly', to: 'posts#add_post_directly'

  get '/privacy_policy', to: 'static_pages#privacy_policy', as: :privacy_policy
  get '/terms_of_use', to: 'static_pages#terms_of_use', as: :terms_of_use
  
  get '/new_temp', to: 'posts#new_temp', as: :new_temp
  
  post 'pusher/auth'

  get 'test', to: 'static_pages#test'

  post 'get_feed', to: 'users#get_feed', as: :get_feed
  post 'mark_read', to: 'users#mark_read', as: :mark_read

end

app/views/layouts/mobile/_duration.mobile.haml
.ui-grid-b.ui-mini
	.ui-block-a
		=link_to 'Hot', (if @post_index then root_path else @tribe end), 'data-ajax'=> false, class: "ui-btn ui-shadow #{'mobile-dr-active' if !@duration_header }"
	.ui-block-b
		%a.ui-btn.ui-shadow{"data-rel" => "popup", "data-transition" => "pop", href: "#popupMenu", class: "#{'mobile-dr-active' if @duration_header && !@new_header}"}
		
			=fa_icon "caret-down"
			- if params[:duration] && params[:duration] != 'current'
				=params[:duration].humanize
			-else
				Top
		#popupMenu{"data-role" => "popup", "data-theme" => "b"}
			%ul{"data-inset" => "true", "data-role" => "listview", style: "min-width:210px;"}
				%li{style:'min-width:210px;'}
					=link_to 'Today', if @post_index then top_path('today') else top_tribe_path(id: @tribe.id, duration: 'today') end, 'data-ajax'=>false
				
				%li{style:'min-width:210px;'}
					=link_to 'This week', if @post_index then top_path('week') else top_tribe_path(id: @tribe.id, duration: 'week') end,'data-ajax'=>false
				%li{style:'min-width:210px;'}
					=link_to 'This month',if @post_index then top_path('month') else top_tribe_path(id: @tribe.id, duration: 'month') end,'data-ajax'=>false
				%li{style:'min-width:210px;'}
					=link_to 'This year', if @post_index then top_path('year') else top_tribe_path(id: @tribe.id, duration: 'year') end ,'data-ajax'=>false
				%li{style:'min-width:210px;'}
					=link_to 'All time', if @post_index then top_path('all_time') else top_tribe_path(id: @tribe.id, duration: 'all_time') end ,'data-ajax'=>false
					
	.ui-block-c
		=link_to 'Latest', if @post_index then new_path('current') else new_tribe_path(id: @tribe.id, duration: 'current') end, class: "ui-btn ui-shadow #{'mobile-dr-active' if @new_header}", 'data-ajax'=>false
		

app/views/layouts/mobile/_flash.mobile.haml
- flash.each do |key, value|
  %div{class: "alert alert-#{key} alert-danger"}
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    %ul
      %li
        = value

app/views/layouts/mobile/_footer.mobile.haml
/ === Footer ===
.footer{id:'footer', 'data-role'=> 'footer', style:'background-color:#585F69;'}
  .container
    .row
      .col-md-4.md-margin-bottom-40
        / About
        .headline
          %h2 About
        %h5.margin-bottom-25.md-margin-bottom-40{style:'color:white'} 
          Niblin is a community of news nibblers. We believe that everything needs to be taken with a pinch of salt and hence there should be a discussion on every news.
          %br
          %strong
            We share relevant links, vote on their relevance and have a healthy discussion on it !!!
      / /col-md-4
      .col-md-4.md-margin-bottom-40
      
      / /col-md-4
      
      / /col-md-4
    / /row
  / /container
/ /footer
/ === End Footer ===
/ === Copyright ===
.copyright
  .container
    .row
      .col-md-6
        %h5.copyright-space{style:'color:white'}
          2014 © Niblin. ALL Rights Reserved.
          =#link_to "Privacy Policy", privacy_policy_path
          
          =#link_to "Terms of Use", terms_of_use_path
      .col-md-6
        =link_to image_tag('logo_150.png', id: 'logo-footer', class: 'pull-right', height:30), root_path
        
    / /row
  / /container
/ /copyright
/ === End Copyright ===
/ JS Global Compulsory

app/views/layouts/mobile/_header.mobile.haml
-@tribes = Tribe.all.order('priority asc')
%div{"data-role" => "header"}
	%ul
		%a.ui-btn.ui-shadow.ui-btn-left.mobile-tribe-drpdwn{"data-rel" => "popup", "data-transition" => "pop", href: "#tribeMenu"}
			= if @tribe.nil? then 'All' else @tribe.name end
			=fa_icon 'caret-down'
		#tribeMenu{"data-role" => "popup", "data-theme" => "a"}
			%ul{"data-inset" => "true", "data-role" => "listview", style: "min-width:210px;"}
				%li{style:'min-width:210px;'}
					=link_to "All", root_path, 'data-ajax'=> false
				-@tribes.each do |tr|
					%li{style:'min-width:210px;'}
						=link_to tr.name, tr, 'data-ajax'=> false

		.center-wrapper
			%span{style:'position:relative; margin-left:-50px;'}
				=link_to image_tag('logo_90.png', alt: 'logo'), root_path
		-if user_signed_in?
			%a.ui-nodisc-icon.ui-alt-icon.ui-btn-right.ui-btn.ui-icon-bars.ui-btn-icon-notext.ui-corener-all{href:"#rightpanel3"}
		-else
			=link_to 'Sign up/Login', new_user_session_path, class: 'ui-btn-right ui-btn ui-btn-inline ui-mini mobile-signup-btn', 'data-transition'=> 'pop', 'data-prefetch'=> true

app/views/layouts/mobile/_messages.mobile.haml
- flash.each do |key, value|
  %div{class: "alert alert-#{key} alert-danger"}
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    %ul
      %li
        = value

app/views/layouts/mobile/_panel.mobile.haml
#rightpanel3{"data-display" => "overlay", "data-position" => "right", "data-role" => "panel", "data-theme" => "a"}
	%h3
	-if user_signed_in?
		.center-wrapper
			%a.ui-btn.ui-corner-all.ui-icon-home.ui-btn-icon-left
				=current_user.username
	.ui-panel-inner
		%ul.ui-listview
			%li.mobile-panel-cont
				%div
					=link_to 'Submit a link', new_temp_path, class: 'ui-btn ui-shadow ui-corner-all ui-btn-b ui-icon-plus ui-btn-icon-left mobile-submit-btn', 'data-ajax'=> false
			
			%li.mobile-panel-cont
				=form_tag search_path, :method => 'get' do
					.ui-field-contain#mobile-search
						%input#search{name: "searchquery", placeholder: "Search Posts", type: "search", value: ""}/

			%li.mobile-panel-cont
				.center-wrapper
					=link_to "Edit Profile", edit_user_registration_path, class: 'ui-btn ui-shadow ui-icon-edit ui-btn-icon-left'
			%li.mobile-panel-cont
				.center-wrapper
					=link_to "My Account",current_user, class: 'ui-btn ui-shadow ui-icon-user ui-btn-icon-left'
			%li.mobile-panel-cont
				.center-wrapper
					=link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'ui-btn ui-shadow ui-icon-power ui-btn-icon-left'
			%li.mobile-panel-cont
				
				%a.ui-btn.ui-shadow.ui-corner-all.ui-icon-delete.ui-btn-icon-left.ui-btn-inline{"data-rel" => "close", href: "#demo-links"} 
					.center-wrapper
						Close panel

app/views/layouts/mobile/_show.mobile.haml
.row
	.col-md-4{id: 'comment-links'}
		%ul.nav.nav-tabs{style:'font-size:14px;'}
			%li{class: "#{'active' if @type == 'top'}"}
				=link_to "Top", p(type:'top')
			%li{class: "#{'active' if @type == 'best'}"}
				=link_to "Best", p(type:'best')
			%li{class: "#{'active' if @type == 'latest'}"}
				=link_to "Latest", p(type:'latest')
			

			

		