config/routes.rb
Phew::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "posts/index"
  devise_for :users,  controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tribes do 
    member do
      get 'tribe/:duration', to: 'tribes#show', as: :top
      get 'new/:duration',   to: 'tribes#show', as: :new  
    end
  end

  resources :sub_tribes do
    member do
      get 'sub_tribe/:duration', to: 'sub_tribes#show', as: :top
      get 'new/:duration', to: 'sub_tribes#show', as: :new  
    end
  end
  
  resources :users do
    member do 
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  

  
  resources :posts do 
    member do
      post "upvote", to: "posts#upvote"
      post "downvote", to: "posts#downvote"
      delete "delete", to: "posts#delete"
      post 'report', to: 'posts#report_post'
    end
    resources :comments do
      member do 
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote" 
        delete "delete", to: "comments#delete"
        post "report", to: 'comments#report_comment'
      end
    end
  end
  root  to: 'posts#index'

  match '/posts/new', to: 'posts#new', via: 'get'

  post 'add_comment', to: 'posts#add_comment'
  post 'add_child_comment', to: 'posts#add_child_comment'
  
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'top/:duration', to: 'posts#index', as: :top
  get 'new/:duration', to: 'posts#index', as: :new
  get 'search', to: 'posts#search'
  
  post 'add_post_directly', to: 'posts#add_post_directly'

  get '/privacy_policy', to: 'static_pages#privacy_policy', as: :privacy_policy
  get '/terms_of_use', to: 'static_pages#terms_of_use', as: :terms_of_use
  
  get '/new_temp', to: 'posts#new_temp', as: :new_temp
  
  post 'pusher/auth'

  get 'test', to: 'static_pages#test'

  post 'get_feed', to: 'users#get_feed', as: :get_feed
  post 'mark_read', to: 'users#mark_read', as: :mark_read

end

app/views/partials/_comment.html.haml
%div.comment-box{id: "comment_#{comment.id}"}
	%h3
		= comment.title
	
	%ul.media-list
		-#%li.comment_box
		%li.media.comment-container
			=#link_to image_tag("avatar.jpg", height:40, width:40,class: 'pull-left'), class: 'media-object'
			.media-body
				.row
					.col-xs-1.col-md-1.text-center
						.row
							=link_to upvote_post_comment_path(@post, comment), method: 'put' do
								%i.fa.fa-arrow-up.fa-lg
						.row
							=comment.likes.size-comment.downvotes.size
						.row
							=link_to downvote_post_comment_path(@post, comment), method: 'put' do
								%i.fa.fa-arrow-down.fa-lg

					.col-xs-11.col-md-11
						.media-heading.commenter-name
							=comment.user.username
						%p.comment-body
							= comment.body
						
						-if user_signed_in? && current_user_commenter?(comment)
							=link_to "Delete", delete_post_comment_path(@post, comment), method: "delete", class: 'delete-link'
						
						-if user_signed_in?
							#reply.reply-link
								%a{style: 'cursor:pointer', onclick: '$(this).parent().next().show(); $(this).parent().hide();'} Reply
							#child{style: "display:none;"}
								=form_tag add_child_comment_path, method: :post, class: 'form-horizontal' do
									.form-group
										=label_tag 'comment', 'Comment',class: 'col-md-2'
										.col-md-6
											=text_area_tag 'comment','', class: 'form-control'
									=hidden_field_tag 'parent_id', comment.id
									=hidden_field_tag 'post_id', @post.id 
									.form-group
										.col-md-offset-2
											=submit_tag 'Submit', class: 'btn'
								%a{onclick: "$(this).parent().hide();$(this).parent().prev().show()", id: 'cancel', style: 'cursor:pointer'}
									Cancel
						
							=link_to "report", report_post_comment_path(@post, comment), method: :post


				= render :partial => 'partials/comment', :collection => comment.children.order('created_at desc')

app/views/partials/_create_link_modal.html.haml
#create-link-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content{id: 'create-link-modal-dialog'}
      .modal-body
        %button.close.font-white{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}
          .font-white
            %strong x
        %h3.modal-title.font-white
          %strong Submit a link
        .row
          .col-md-12
            %p.font-white
              Enter the link of an article, image or video
            =form_tag new_post_path, class: 'form form-horizontal', role: 'form', method: 'get' do
              .form-group
                .col-md-8
                  =url_field_tag 'url', '', type: 'email', class: 'form-control', placeholder: 'http://'
                =submit_tag 'Refine & Submit', class: 'btn btn-success control-label'
        

:javascript
  $(function() {
    $(' #post_tags_list').select2({tags:[],tokenSeparators: [",", " "]})
  });

          