config/routes.rb
Phew::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "posts/index"
  devise_for :users,  controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tribes do 
    member do
      get 'tribe/:duration', to: 'tribes#show', as: :top
      get 'new/:duration',   to: 'tribes#show', as: :new  
    end
  end

  resources :sub_tribes do
    member do
      get 'sub_tribe/:duration', to: 'sub_tribes#show', as: :top
      get 'new/:duration', to: 'sub_tribes#show', as: :new  
    end
  end
  
  resources :users do
    member do 
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  

  
  resources :posts do 
    member do
      post "upvote", to: "posts#upvote"
      post "downvote", to: "posts#downvote"
      delete "delete", to: "posts#delete"
      post 'report', to: 'posts#report_post'
    end
    resources :comments do
      member do 
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote" 
        delete "delete", to: "comments#delete"
        post "report", to: 'comments#report_comment'
      end
    end
  end
  root  to: 'posts#index'

  match '/posts/new', to: 'posts#new', via: 'get'

  post 'add_comment', to: 'posts#add_comment'
  post 'add_child_comment', to: 'posts#add_child_comment'
  
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'top/:duration', to: 'posts#index', as: :top
  get 'new/:duration', to: 'posts#index', as: :new
  get 'search', to: 'posts#search'
  
  post 'add_post_directly', to: 'posts#add_post_directly'

  get '/privacy_policy', to: 'static_pages#privacy_policy', as: :privacy_policy
  get '/terms_of_use', to: 'static_pages#terms_of_use', as: :terms_of_use
  
  get '/new_temp', to: 'posts#new_temp', as: :new_temp
  
  post 'pusher/auth'

  get 'test', to: 'static_pages#test'

  post 'get_feed', to: 'users#get_feed', as: :get_feed
  post 'mark_read', to: 'users#mark_read', as: :mark_read

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :text
#  link             :text
#  description      :text
#  user_id          :integer
#  tribe_id         :integer
#  created_at       :datetime
#  updated_at       :datetime
#  hotness          :float
#  netvotes         :integer          default(0)
#  pic_file_name    :string(255)
#  pic_content_type :string(255)
#  pic_file_size    :integer
#  pic_updated_at   :datetime
#  source           :string(255)
#  sub_tribe_id     :integer
#  slug             :string(255)
#

class Post < ActiveRecord::Base
	
	has_attached_file :pic, :path => "posts/pics/000/000/:id/:style/:filename", styles: {
	    thumb: '100x100#',
	    square: '200x200#',
	    medium: '300x300>'
  	}
  	
  	# Validate the attached image is image/jpg, image/png, etc
 	validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/
 	
	validates :title, presence: true
	validates :user_id, presence: true
	
	belongs_to :user
	belongs_to :tribe
	belongs_to :sub_tribe
	
	has_many :comments

	has_many :reports, as: :reportable
	acts_as_votable
	acts_as_commentable
	acts_as_taggable_on :tags

	#Friendly Id
	extend FriendlyId
	friendly_id :title, use: [:slugged, :history]

	def should_generate_new_friendly_id?
	  title_changed?
	end
	## End of friendly Id

	def self.refresh_hotness(post)
		hotness = Post.hot(post)
		post.hotness = hotness
		post.save
	end

	def self.today
	  where("created_at >= ?", Time.zone.now - 24*60*60)
	end
	
	def self.week
	  where("created_at >= ?", Time.zone.now - 7*24*60*60)
	end

	def self.month
	  where("created_at >= ?", Time.zone.now - 30*24*60*60)
	end

	def self.year
	  where("created_at >= ?", Time.zone.now - 365*24*60*60)
	end

	def self.total_posts_of_user(user)
	end
	
	def self.refresh_votes(post)
		votes =post.likes.size-post.downvotes.size
    	post.netvotes = votes
    	post.save
	end

	def test_notify
		
		Pusher.url = "http://6b2448376d4955fa296c:77c911158c8bf9314a4b@api.pusherapp.com/apps/76475"

		Pusher['test_channel'].trigger('my_event', {
		  message: 'hello alok'
		})
	end
	#handle_asynchronously :test_notify

	private
		def self.hot(post)
			# The hot formula
			ups = post.upvotes.size
			downs = post.downvotes.size
			date = post.created_at

			s = Post.score(ups,downs)
			order = Math.log10([s.abs,1].max)

			if s> 0
				sign = 1
			elsif s< 0
				sign = -1
			else 
				sign = 0
			end

			seconds = Post.epoch_seconds(date) - 1134028003
			return (sign*order + seconds/45000).round(7)
		end
		def self.epoch_seconds(date)
			epoch = DateTime.new(1988,1,1)
			# Returns the number of seconds from the epoch to date
			return date-epoch
		end

		def self.score(ups, downs)
			return ups-downs
		end
		
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
  require 'open-uri'
  require 'nokogiri'
  require 'fastimage'
  has_mobile_fu_for :index, :upvote, :downvote
  before_filter :authenticate, except: [:index, :show, :search]  
  
  include Feed

  def index
    links_per_page = 10
      
    @post_index = true
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).order("hotness desc").page(params[:page]).per(links_per_page)
    elsif params[:duration]
      duration = params[:duration]
        @duration_header = true
        case duration
          when 'current'
            @new_header = true
            @posts = Post.all.order('created_at desc').page(params[:page]).per(links_per_page)
          when 'today'
            @posts = Post.today.order('netvotes desc','created_at desc').page(params[:page]).per(links_per_page)
          when 'week'
            @posts = Post.week.order('netvotes desc' , 'created_at desc').page(params[:page]).per(links_per_page)
          when 'month' 
            @posts = Post.month.order('netvotes desc' , 'created_at desc').page(params[:page]).per(links_per_page)
          when 'year'
            @posts = Post.year.order('netvotes desc' , 'created_at desc').page(params[:page]).per(links_per_page)
          when 'all_time'
            @posts = Post.all.order('netvotes desc' , 'created_at desc').page(params[:page]).per(links_per_page)
        end
    elsif params[:host]
        source = params[:host]
        @posts = Post.order("hotness desc").page(params[:page]).per(links_per_page)
    else
      @posts = Post.all.order("hotness desc").page(params[:page]).per(links_per_page)
    end
    

  end

  ## Controller for mobile
  def new_temp
  end
  
  def new
  	@url = params[:url]
    
    if @url.present?
      @title = get_title(@url)
      @source = get_host(@url)
      @descrip = get_descrip(@url)
    end
    @post = Post.new
    @tribes = Tribe.all
    @trending_tribes = TrendingTribe.all

    #@images = get_images(@url)
    ##It will be better to move this job in background
  end

  def add_post_directly
    @url = params[:link]

    post = current_user.posts.new

    if @url.present?
      
      @title = get_title(@url)
      @source = get_host(@url)
      @descrip = get_descrip(@url)
      
      post.link = @url
      post.title = @title
      post.source = @source
      post.description = @descrip
      post.tag_list.add(params[:tag_list], parse: true)
      
      #assigning the tribe
      tribe = Tribe.find(params[:tribe])
      post.tribe_id = tribe.id

      #image link
      @image_link = get_images(@url)
      post.pic = get_image_from_url(@image_link)

      if post.save
        Post.refresh_hotness(post)
        flash[:success] = 'Successfully posted'
        redirect_to root_path
      else
        flash[:error] = 'Some error occurred'
        redirect_to new_post_path
      end
    else
      flash[:error] = 'Link not provided, please provide the link and try again'
      redirect_to root_path
    end

  end

  def create
    post = current_user.posts.create(post_params)
  	
    #assigning the tribe
    if params[:post][:tribe]
      tribe = Tribe.find(params[:post][:tribe])
      post.tribe_id = tribe.id
    end
    
    #assigning the sub tribe if present
    if params[:post][:sub_tribe]
      stribe = SubTribe.find(params[:post][:sub_tribe])
      post.sub_tribe_id = stribe.id
    end
    #assigning the source
    @uri = URI.parse(params[:post][:link])
    post.source = @uri.host

    #image link
    @image_link = get_images(@uri)
    post.pic = get_image_from_url(@image_link)
    

    if post.save
      Post.refresh_hotness(post)
      flash[:success] = 'Successfully posted'
      redirect_to root_path
  	else
      flash[:error] = 'Some error occurred'
      redirect_to new_post_path
  	end
  end

  def show
    @post = Post.friendly.find(params[:id])
    if request.path != post_path(@post)
      redirect_to @post, status: :moved_permanently
    end

    @post_show = true
    @tribes = Tribe.all
    @type = 'top'
    if params[:type]
      type = params[:type]
      case type
        when 'best'
          @type = 'best'
          @root_comments = @post.root_comments.order('hotness desc')
        when 'latest'
          @type = 'latest'
          @root_comments = @post.root_comments.order('created_at desc')
        else
          @root_comments = @post.root_comments.order('netvote desc', 'created_at desc')
      end
    else
      @root_comments = @post.root_comments.order('netvote desc', 'created_at desc')
    end
  end

  def search
    links_per_page = 10
    @posts= Post.search(params[:searchquery]).page(params[:page]).per(links_per_page)
  end

  def delete
    @post = Post.friendly.find(params[:id])
    @post.destroy
    redirect_to :back
  end

  def add_comment
    if user_signed_in?
      post_id = params[:post_id]
      comment = params[:comment]
      @post = Post.friendly.find(post_id)
      @user_who_commented = current_user
      @comment = Comment.build_from( @post, @user_who_commented.id, comment )
      if @comment.save
          flash[:success] = "Successfully saved"
          Noti.add_comment_noti(post_id, current_user.id)
      else
        @err = @comment.errors
      end
      redirect_to :back
    else
      redirect_to '/users/sign_in'
    end
  end

  def upvote
    @post = Post.friendly.find(params[:id])
    @post.liked_by current_user
    Post.refresh_votes(@post)
    if @post.save
      Post.refresh_hotness(@post)
      respond_to do |format|
        format.html {redirect_to :back}
        format.mobilejs 
        format.js
      end
    end
  end
  
  def downvote
    @post = Post.friendly.find(params[:id])
    @post.downvote_from current_user
    Post.refresh_votes(@post)
    if @post.save
      Post.refresh_hotness(@post)
      respond_to do |format|
        format.html {redirect_to :back}
        format.mobilejs
        format.js 
      end
    end

  end

  def add_child_comment
    if user_signed_in?
      post_id = params[:post_id]
      parent_id = params[:parent_id]
      comment = params[:comment]

      @post = Post.friendly.find(post_id)
      parent_comment = Comment.find(parent_id)


      @user_who_commented = current_user
      @comment = Comment.build_from(@post, @user_who_commented.id, comment)
      
      if @comment.save
        @comment.move_to_child_of(parent_comment)
        
        flash[:success] = "Successfully saved"
      else
        flash[:warning] = "#{@comment.errors.full_messages}"
      end
      redirect_to :back
    else
      redirect_to '/users/sign_in'
    end
  end

  def report_post
    post_id = params[:id]
    post = Post.friendly.find(post_id)
    r = post.reports.find_or_create_by(user_id: current_user.id)
    if r
      flash[:success] = "Reported Successfully"
    else
      flash[:error] = "Some error occured"
    end
    redirect_to :back
  end



  private 

    def post_params
	  	params.require(:post).permit(:title, :link,:description, :tag_list, :pic)
	  end
    
    def get_title(link)
      doc = Nokogiri::HTML(open(link))
      if doc.at_css("h1")
        doc.at_css("h1").text 
      else
        ""
      end
    end

    def get_host(link)
      s = URI.parse(link)
      source = s.host
      if source
        return source
      else
        return "no source found"
      end
    end

    def get_image_from_url(url)
      begin 
        open(url)
      rescue 
        ""
      end
    end

    def get_descrip(link)
      page = Nokogiri::HTML(open(link)) 
      descp = page.css("meta[name='description']")[0]
      if descp
        description = descp['content']
      else 
        description = "none"
      end

    end

    def process_page(url)
      doc = Nokogiri(open(url))
    end

    def process_images(doc)
      images = doc.css('img')
    end


    def get_images(url)
      page = Nokogiri::HTML(open(url)) 
      chk_og = page.css("meta[property='og:image']")[0]
      if chk_og
        image_link = chk_og['content']
      else 
        image_link = get_first_elligible_image(page)
      end
    end

    def get_first_elligible_image(page)
      img_pth_content = page.xpath("//img[not(ancestor::*[contains(@id, 'sidebar') or contains(@id, 'comment') or contains(@id, 'footer') or contains(@id, 'header')]) and ancestor::*[contains(@id, 'content')]]/@src")
      img_pth_all = page.xpath("//img[not(ancestor::*[contains(@id, 'sidebar') or contains(@id, 'comment') or contains(@id, 'footer') or contains(@id, 'header')])]/@src")
      
      img_paths = if img_pth_content.empty? then img_pth_all else img_pth_content end

      res_path = ""
      img_paths.each do |pth|
          width, len= get_size(pth)
          res_path = pth
          if width>100 && len >100 && (width/len)<3
            break
          else 
            res_path = ""
          end
      end
      res_path
    end

    def get_size(img_pth)
      begin
        size = FastImage.size(img_pth,:raise_on_failure=>true, :timeout=>2.0)
        width = size[0]
        len = size[1]
      rescue
        size = [1,1]
        width = size[0]
        len = size[1]
      end
      return width, len
    end

    def authenticate
      if !user_signed_in?
        redirect_to new_user_session_path
      end
    end

    def get_tribe(tribe)
      Tribe.find_by(name: tribe)
    end

    def get_feed
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper

	def top_comment(post_id)
		post = Post.find(post_id)

		@top_comment_arr = post.root_comments.order('netvote desc, created_at desc').limit(1)
		if @top_comment_arr.empty?
			@top_comment = nil
		else
			@top_comment = @top_comment_arr[0]
		end
	end

	def comment_count(post_id)
		post = Post.find(post_id)

		@com_count = post.comment_threads.size
	end

	def current_user_poster?(post)
		return true if post.user_id == current_user.id
	end
	


	def nested_li(objects, &block)
		objects = objects.order(:lft) if objects.is_a? Class

		return '' if objects.size == 0

		output = '<ul><li>'
		path = [nil]

		objects.each_with_index do |o, i|
		    if o.parent_id != path.last
		      # We are on a new level, did we descend or ascend?
		      if path.include?(o.parent_id)
		        # Remove the wrong trailing path elements
		        while path.last != o.parent_id
		          path.pop
		          output << '</li></ul>'
		        end
		        output << '</li><li>'
		      else
		        path << o.parent_id
		        output << '<ul><li>'
		      end
		    elsif i != 0
		      output << '</li><li>'
		    end
		    output << capture(o, path.size - 1, &block)
		  end

		  output << '</li></ul>' * path.length
		  output.html_safe
	end

	def refersh_hotness(post)
		hotness = hot(post)
		post.hotness = hotness
		post.save
	end

	
	private
		def hot(post)
			# The hot formula
			ups = post.upvotes.size
			downs = post.downvotes.size
			date = post.created_at

			s = score(ups,downs)
			order = Math.log10([s.abs,1].max)

			if s> 0
				sign = 1
			elsif s< 0
				sign = -1
			else 
				sign = 0
			end

			seconds = epoch_seconds(date) - 1134028003
			return (sign*order + seconds/45000).round(7)
		end

		def epoch_seconds(date)
			epoch = DateTime.new(1988,1,1)
			# Returns the number of seconds from the epoch to date
			return date-epoch
		end

		def score(ups, downs)
			return ups-downs
		end

end

app/views/posts/_comment.html.haml
%div.comment-box{id: "comment_#{comment.id}"}
	%h3
		= comment.title
	%ul.media-list
		-#%li.comment_box
		%li.media.comment-container
			=#link_to image_tag("avatar.jpg", height:40, width:40,class: 'pull-left'), class: 'media-object'
			.media-body
				.row
					.col-xs-12.col-md-12
					
						.media-heading.commenter-name
							=comment.user.username
							%span.comment_time
								=time_ago_in_words(comment.created_at)
								ago
						%p.comment-body
							= raw(comment.body)
						=link_to upvote_post_comment_path(@post, comment), method: 'put', class: 'comment-vote-arrow' do
							=fa_icon "chevron-up"
						%span
							=comment.likes.size-comment.downvotes.size
						=link_to downvote_post_comment_path(@post, comment), method: 'put', class: 'comment-vote-arrow' do
							=fa_icon "chevron-down"
						&nbsp
						
						
						-if user_signed_in?
							%span.reply-link{id:'reply'}
								%a{style: 'cursor:pointer', onclick: '$(this).parent().next().show(); $(this).parent().hide();'} reply
							
							%span{style: "display:none;", id: 'child'}
								=form_tag add_child_comment_path, method: :post, class: 'form-horizontal' do
									.form-group
										=label_tag 'comment', 'Comment',class: 'col-md-2'
										.col-md-6
											=text_area_tag 'comment','', class: 'form-control'
									=hidden_field_tag 'parent_id', comment.id
									=hidden_field_tag 'post_id', @post.id 
									.form-group
										.col-md-offset-2
											=submit_tag 'Submit', class: 'btn'
								%a{onclick: "$(this).parent().hide();$(this).parent().prev().show()", id: 'cancel', style: 'cursor:pointer'}
									cancel
							-if user_signed_in? && current_user_commenter?(comment)
								=link_to "delete", delete_post_comment_path(@post, comment), method: "delete", class: 'delete-link'
							&nbsp
							=link_to "report", report_post_comment_path(@post, comment), method: :post, class: 'report-link'


				= render :partial => 'comment', :collection => comment.children.order('created_at desc')

app/views/posts/_comment.mobile.haml
%div.comment-box{id: "comment_#{comment.id}"}
	%h3
		= comment.title
	
	%ul.media-list
		-#%li.comment_box
		%li.media.mobile-comment-container
			=#link_to image_tag("avatar.jpg", height:40, width:40,class: 'pull-left'), class: 'media-object'
			.media-body
				.row
					.col-xs-12
						
						.media-heading.commenter-name
							=comment.user.username
							%span.comment_time
								=time_ago_in_words(comment.created_at)
								ago
						%p.comment-body
							= comment.body
						
						=link_to upvote_post_comment_path(@post, comment), method: 'put' do
							=fa_icon "chevron-up"
						%span.mobile-net-vote
							=comment.likes.size-comment.downvotes.size
						
						=link_to downvote_post_comment_path(@post, comment), method: 'put' do
							=fa_icon "chevron-down"
						&nbsp
						
						&nbsp
						-if user_signed_in?
							%span.reply-link{id: 'reply'}
								%a{style: 'cursor:pointer', onclick: '$(this).parent().next().show(); $(this).parent().hide();'} reply
							
							%span{id: 'child',style: "display:none;"}
								=form_tag add_child_comment_path, method: :post do
									.form-group
										=label_tag 'comment', 'Comment',class: 'col-md-2'
										.col-md-6
											=text_area_tag 'comment','', class: 'form-control'
									=hidden_field_tag 'parent_id', comment.id
									=hidden_field_tag 'post_id', @post.id 
									.form-group
										.col-md-offset-2
											=submit_tag 'Submit', class: 'btn'
								%a{onclick: "$(this).parent().hide();$(this).parent().prev().show()", id: 'cancel', style: 'cursor:pointer'}
									%span{style:'font-size:12px;'}
										cancel
						
							=link_to "report", report_post_comment_path(@post, comment), method: :post, class: 'mobile-report-comment'

						-if user_signed_in? && current_user_commenter?(comment)
							=link_to "delete", delete_post_comment_path(@post, comment), method: "delete", class: 'delete-link'
						
				= render :partial => 'comment', :collection => comment.children.order('created_at desc')

app/views/posts/_post.html.haml
-#.panel.panel-default.post_panel
.post-container
	.row
		.col-md-1.text-center.vote-cont
			.up-down-vote-box{style:'background-color:white; line-height:10px;'}
				=button_to upvote_post_path(p), method: 'post', remote:true, class: 'upvote-btn' do
					%h4
						.vote-arrow{class: "#{'upvoted' if user_signed_in? && current_user.voted_up_on?(p)}", id: "upvote-#{p.id}"}
							=fa_icon "chevron-up"
					
						=#image_tag "arrow-up.png", height:25, width:20
						=#fa_icon "arrow-up 2x"
				.net-vote
					%strong{id: "netvote-#{p.id}", class: "#{'upvoted' if user_signed_in? && current_user.voted_up_on?(p)} #{'downvoted' if user_signed_in? && current_user.voted_down_on?(p)} "} 
						=p.likes.size-p.downvotes.size
								
				%div
					=button_to downvote_post_path(p), method: 'post', remote:true, class: 'downvote-btn' do
						%h4
							.vote-arrow{class: "#{'downvoted' if user_signed_in? && current_user.voted_down_on?(p)}", id: "downvote-#{p.id}"}
								=fa_icon "chevron-down"
						
		.col-md-1.post-image-cont
			- if p.pic.url(:square) != '/pics/thumb/missing.png'
				=link_to image_tag(p.pic.url(:square), alt: 'post photo', height:130, class: 'post-img'), p
			-else 
				=image_tag 'lamp_post.jpg', alt:'post photo', height:130, class: 'post-img'
		.col-md-8.post-mid-part.col-md-offset-1
			.row
				.col-md-11
					=link_to "#{p.title}", p.link,target:'_blank', class: 'title-of-link'
					-if p.source?
						%span.source_link
							(
							=p.source
							)
				.col-md-1
					.pull-right
						-if user_signed_in?
							%a.dropdown-toggle{"data-toggle" => "dropdown", href: "#", "data-toggle"=>"dropdown", "data-hover"=>"dropdown", "data-delay"=>"30","data-close-others"=>"false"}
								=fa_icon "caret-down"
							%ul.dropdown-menu
								%li
									=link_to "report", report_post_path(p), method: :post
								-if current_user_poster?(p)
									%li.divider
									%li
										=link_to "delete", delete_post_path(p), method: "delete", class: 'delete-post'
					
			.link_descrip
				=truncate(p.description, length:400)
				.margin-bottom-5
				.row	
					.col-md-12
						-tags = p.tag_list
						- if tags.any?
							-tags.each do |t|
								%span
									=link_to t, tag_path(t), class: 'tag'
				
			.row.post_footer			
				.col-md-6
					=fa_icon "clock-o"
					=time_ago_in_words(p.created_at)
					ago by
					
					%span
						=link_to p.user.username, p.user, class: 'user-link'
					(
					= pluralize(p.user.followers.count, 'follower')
					)

					-if p.tribe
						to
						=p.tribe.name
					- if p.tribe && p.sub_tribe
						and
					- if p.sub_tribe
						to
						=p.sub_tribe.name
					
				.col-md-6.comment-count-cont
					= link_to p do 
						=fa_icon "comments"
						=pluralize(comment_count(p.id), 'comment')
						- tc = top_comment(p.id)
						
						-if tc.present?
							(
							Top commenter - 
							=link_to tc.user.username, tc.user, class: 'top-commenter'
							)
	

app/views/posts/search.mobile.haml
%div{'data-role'=> 'page','data-url'=> "#{request.path}", id: 'search-results', "data-dom-cache"=>"true"}
	= render 'layouts/mobile/panel'
	%div{"data-role" => "header"}
		= render 'layouts/mobile/header'
	.ui-content{role: "main", style:'padding-left:2px; padding-right:2px; padding-top:0px;'}
		=render 'layouts/mobile/flash'
		=form_tag search_path, :method => 'get' do
			.ui-field-contain#mobile-search
				%input#search{name: "searchquery", placeholder: "Search Posts", type: "search", value: ""}/

		-@posts.each do |p|
			= render 'post', :p=> p
		=paginate @posts
	%div{"data-role" => "footer"}
		= render 'layouts/mobile/footer'

app/views/posts/show.html.haml
.row{id: 'comments-page-cont'}
	.col-md-10.col-md-offset-1
		- flash.each do |key, value|
			:javascript
				toastr.options.timeOut= "1500"
				toastr.success("#{value}");
		%h2
			=link_to @post.title, @post.link, target: '_blank', class: 'post-title-comment-page'
		.row
			.col-md-8
				=@post.description
			.col-md-2
				.user-detail-box-comment-page
					Submited
					=time_ago_in_words(@post.created_at)
					ago by
					%strong 
						=link_to @post.user.username, @post.user
		-if user_signed_in?
			.row
				.col-md-8
					=form_tag add_comment_path, method: :post, class:'form-inline' do
						.form-group
							=label_tag 'Comment'
						.form-group
							=text_area_tag 'comment',"", class: 'comment-input'
						=hidden_field_tag 'post_id', @post.id
						=submit_tag 'Submit', class: 'btn btn-success'
		-else
			%h4
				=link_to('Sign in to add comments or to reply to comments', new_user_session_path) 

		-if !@root_comments.empty?		
			=render 'layouts/show'
			#comments
				-@root_comments.each do |comment|
					=render :partial => 'comment', :object => comment
		-else
			.row
				.col-md-6.col-md-offset-2
					%p
						&nbsp
						Be the first one to comment
		.div{style:'margin-bottom:60px;'}		

:javascript
	$('.comment-vote-arrow').click(function(){
		var signed_in = #{user_signed_in?};
		if(signed_in){
		}
		else{
			notify('Please Sign in to vote!', 'error', 2000);
		}
	});

	

app/views/posts/show.mobile.haml
%div{'data-role'=> 'page','data-url'=> "#{request.path}"}
	= render 'layouts/mobile/panel'
	%div{"data-role" => "header"}
		= render 'layouts/mobile/header'
	.ui-content{role: "main", style:'padding-left:2px;'}	
		=render 'layouts/mobile/flash'
		%h4{style: 'paddin-top:5px;'}
			=link_to @post.title, @post.link, target: '_blank'
		%p.mobile-post-descrip
			=@post.description
		-tags = @post.tag_list
		-if !tags.empty?
			%ul.list-inline
				Tags:
				-tags.each do |t|
					%li
						=link_to t, tag_path(t), class: 'mobile-tag'
		-if user_signed_in?
			%div.mobile-write-comment-cont
				=form_tag add_comment_path, method: :post, class:'form-inline' do
					.ui-field-contain
						=label_tag 'Comment'
					.ui-field-contain
						=text_area_tag 'comment',"", type:'text'
					=hidden_field_tag 'post_id', @post.id
					.ui-field-contain
						=submit_tag 'Submit', class: 'btn btn-success'
		-else
			%h4
				=link_to('Sign in to add comments or to reply to comments', new_user_session_path) 
		-if !@root_comments.empty?		
			=render 'layouts/mobile/show'
			#comments
				-@root_comments.each do |comment|
					=render :partial => 'comment', :object => comment
		-else
			.row
				.col-md-6.col-md-offset-2
					%p
						&nbsp
						Be the first one to comment
	%div{"data-role" => "footer"}
		= render 'layouts/mobile/footer'