config/routes.rb
Phew::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "posts/index"
  devise_for :users,  controllers: { registrations: "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tribes do 
    member do
      get 'tribe/:duration', to: 'tribes#show', as: :top
      get 'new/:duration',   to: 'tribes#show', as: :new  
    end
  end

  resources :sub_tribes do
    member do
      get 'sub_tribe/:duration', to: 'sub_tribes#show', as: :top
      get 'new/:duration', to: 'sub_tribes#show', as: :new  
    end
  end
  
  resources :users do
    member do 
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  

  
  resources :posts do 
    member do
      post "upvote", to: "posts#upvote"
      post "downvote", to: "posts#downvote"
      delete "delete", to: "posts#delete"
      post 'report', to: 'posts#report_post'
    end
    resources :comments do
      member do 
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote" 
        delete "delete", to: "comments#delete"
        post "report", to: 'comments#report_comment'
      end
    end
  end
  root  to: 'posts#index'

  match '/posts/new', to: 'posts#new', via: 'get'

  post 'add_comment', to: 'posts#add_comment'
  post 'add_child_comment', to: 'posts#add_child_comment'
  
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'top/:duration', to: 'posts#index', as: :top
  get 'new/:duration', to: 'posts#index', as: :new
  get 'search', to: 'posts#search'
  
  post 'add_post_directly', to: 'posts#add_post_directly'

  get '/privacy_policy', to: 'static_pages#privacy_policy', as: :privacy_policy
  get '/terms_of_use', to: 'static_pages#terms_of_use', as: :terms_of_use
  
  get '/new_temp', to: 'posts#new_temp', as: :new_temp
  
  post 'pusher/auth'

  get 'test', to: 'static_pages#test'

  post 'get_feed', to: 'users#get_feed', as: :get_feed
  post 'mark_read', to: 'users#mark_read', as: :mark_read

end

app/views/layouts/_footer.html.haml
/ === Footer ===
.footer{id:'footer'}
  .container
    .row
      .col-md-4.md-margin-bottom-40
        / About
        .headline
          %h2 About
        %p.margin-bottom-25.md-margin-bottom-40 
          Niblin is a community of news nibblers. We believe that everything needs to be taken with a pinch of salt and hence there should be a discussion on every news.
          %br
          %strong
            We share relevant links, vote on their relevance and have a healthy discussion on it !!!
      / /col-md-4
      .col-md-4.md-margin-bottom-40
      
      / /col-md-4
      
      / /col-md-4
    / /row
  / /container
/ /footer
/ === End Footer ===
/ === Copyright ===
.copyright
  .container
    .row
      .col-md-6
        %p.copyright-space
          2014 © Niblin. ALL Rights Reserved.
          =link_to "Privacy Policy", privacy_policy_path
          |
          =link_to "Terms of Use", terms_of_use_path
      .col-md-6
        =link_to image_tag('logo_150.png', id: 'logo-footer', class: 'pull-right', height:30), root_path
        
    / /row
  / /container
/ /copyright
/ === End Copyright ===
/ JS Global Compulsory

app/views/layouts/_header.html.haml
%nav.navbar{role: "navigation", id: 'top-nav'}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: root_path, style: "padding-top:5px;"} 
      =image_tag 'logo_150.png', height: 45
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li{id: 'top-nav-create-btn-cont'}
        =link_to (fa_icon "plus-circle", class: 'color-light-green', text: 'Submit a new link'), '#',  id: 'submit-new-link','data-toggle'=>"modal" ,'data-target'=>"#create-link-modal", class: 'btn btn-default top-nav-create-btn'
    
    %ul.nav.navbar-nav.navbar-right
      
      %li{style:'display:none'}
        =form_tag search_path, :method => 'get', class: 'navbar-right navbar-form ' do
          .form-group
            .input-group
              .input-group-addon
                =fa_icon 'search'
              =text_field :searchquery, '', class: 'form-control', placeholder:'Search...'
      
      -if user_signed_in?
        %li
          =render 'layouts/notification'

        %li{style:'margin-right:7px; margin-left:7px;'}
          .btn-group{style: 'cursor:pointer;'}
            #user-name-nav{"data-toggle" => "dropdown", href: "#", "data-toggle"=>"dropdown", "data-hover"=>"dropdown", "data-delay"=>"10","data-close-others"=>"false"}
              =fa_icon "user"
              =current_user.username
              =fa_icon "caret-down"
            %ul.dropdown-menu.user-drp-dwn
              %li
                =link_to 'My Account', current_user
              %li.divider
              %li
                =link_to 'Sign out', destroy_user_session_path, method: 'delete'      
      -else
        %li
          =link_to "Sign Up", new_user_registration_path, style:'font-weight:bold;'
        %li.devider
        %li
          =link_to('Login', new_user_session_path, style: 'font-weight:bold;')
        


/ Modal
=render 'partials/create_link_modal'
-##notify
-if user_signed_in?
  :javascript
    $(function(){
      $.post( "#{get_feed_path}");
    });

app/views/layouts/_index.html.haml
%nav.navbar{id: 'refine-nav'}
  .row{style:'margin-right:0px !important; margin-left:0px !important;'}  
    .col-md-5{id: "duration-header", style: 'padding-left:20px; padding-top:5px;'}
      %ul.nav.nav-pills.refine-top
        %li.refine-link{class: "#{'active' if !@duration_header }"}
          
          =link_to 'Hot', (if @post_index then root_path else @tribe end)

        %li.refine-link{class: "#{'active' if @duration_header && !@new_header}"}
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#", "data-toggle"=>"dropdown", "data-hover"=>"dropdown", "data-delay"=>"30","data-close-others"=>"false"}
            Top
            =fa_icon "caret-down"
          %ul.dropdown-menu
            %li
              =link_to 'Today', if @post_index then top_path('today') else top_tribe_path(id: @tribe.id, duration: 'today') end
            %li.divider
            %li
              =link_to 'This week', if @post_index then top_path('week') else top_tribe_path(id: @tribe.id, duration: 'week') end
            %li.divider
            %li
              =link_to 'This month',if @post_index then top_path('month') else top_tribe_path(id: @tribe.id, duration: 'month') end
            %li.divider
            %li
              =link_to 'This year', if @post_index then top_path('year') else top_tribe_path(id: @tribe.id, duration: 'year') end
            %li.divider
            %li
              =link_to 'All time', if @post_index then top_path('all_time') else top_tribe_path(id: @tribe.id, duration: 'all_time') end
        %li.refine-link{class: "#{'active' if @new_header}"}
          =link_to 'Latest', if @post_index then new_path('current') else new_tribe_path(id: @tribe.id, duration: 'current') end

        %li
          =link_to (fa_icon "plus-circle", class: 'color-light-green', text: 'Submit a new link'), '#', id: 'submit-new-link-refine','data-toggle'=>"modal" ,'data-target'=>"#create-link-modal", style: 'display:none', class: 'btn btn-default'
    .col-md-7
      .nav.navbar-nav.navbar-right
        %button.btn-u.btn-u-default.dropdown-toggle{"data-toggle" => "dropdown", href: "#", "data-toggle"=>"dropdown", "data-hover"=>"dropdown", "data-delay"=>"30","data-close-others"=>"false", id: 'tribe-toggle'}
          - if @tribe
            =@tribe.name
          -else
            Browse by Tribes
          =fa_icon "caret-down"
        %ul.dropdown-menu{style:'padding-bottom:0px; padding-top:0px;'}
          %li
            =link_to root_path, style: 'padding-top:8px !important; padding-bottom:8px !important;'  do 
              All
          %li.divider{style: 'margin-bottom:0px; margin-top:0px;'}
          -Tribe.all.each do |t|
            %li
              =link_to t, style: 'padding-top:8px !important; padding-bottom:8px !important;'  do 
                =t.name
          
            %li.divider{style: 'margin-bottom:0px; margin-top:0px;'}


    
:javascript
  

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
   	
    <script type="text/javascript">
   		toastr.success("<%= value %>");
	</script>

<%end %>

app/views/layouts/_notification.html.haml
%a{id: 'notification-holder', 'data-toggle'=>'tooltip', 'data-placement'=>'top', 'title'=> 'this is a tooltip', style:'cursor:pointer'}
	%span{style:"color:black"}
		=fa_icon "bell-o lg"
	-if current_user.urn>0
		%span{id:'notification-text'}
			=current_user.urn

.messagepop.pop
	-#%a.noti-close.pull-right{style: 'color:#A9A9A9; cursor:pointer'}
	.row
		.col-md-12.notification-heading
			%strong
				Notifications
	#no_more_noti_plc
	-noti = Noti.get_notis(current_user.id)
	-if current_user.urn && current_user.urn >0
		-noti.each do |n|
			- if !n.is_read
				.row.noti-row{class: "#{'unread' if !n.is_read}"}
					.col-md-11
						-u = User.find(n.actor)
						=link_to u.username, u
						-if n.verb =='post_comment'
							commented on your post
							-p = Post.find(n.object)
							=link_to p.title, p

					.col-md-1.pull-left{onmouseover: 'goLight(this)', onmouseout: 'goDark(this)', style: 'cursor:pointer'}
						=link_to mark_read_path(id: n.id), method: 'post', remote: true, onClick:'hideIt(this)', class: 'dismiss-noti' do
							=fa_icon 'times'				
	-else
		No new notifications
					
	
:javascript
	function deselect(e) {
	  $('.pop').slideFadeToggle(function() {
	    e.removeClass('selected');
	  });    
	}

	$(function() {
	  $('#notification-holder').on('click', function() {
	    if($(this).hasClass('selected')) {
	      deselect($(this));               
	    } else {
	      $(this).addClass('selected');
	      $('.pop').slideFadeToggle();
	    }
	    return false;
	  });

	  $('.noti-close').on('click', function() {
	    deselect($('#notification-holder'));
	    return false;
	  });
	});

	$.fn.slideFadeToggle = function(easing, callback) {
	  return this.animate({ opacity: 'toggle', height: 'toggle' }, 'fast', easing, callback);
	};

	function goLight(x) {
		x.style.color = '#AAAAAA';
	}

	function goDark(x){
		x.style.color = '#555555';
	}

	function hideIt(x){
		y = $(x).parent();
		z = $(y).parent();
		$(z).fadeOut('slow');
	}

app/views/layouts/_post_show.html.haml
.row{id:'post-show-top-img-cont'}
	.col-md-12.overlay-post-show
		.row
			.col-md-10.col-md-offset-1
				.margin-bottom-20
				#comments-title.text-center
					Comments
						
				

app/views/layouts/_show.html.haml
.margin-bottom-10
.row
	.col-md-4{id: 'comment-links'}
		%ul.nav.nav-tabs
			%li{class: "#{'active' if @type == 'top'}"}
				=link_to "Top", p(type:'top')

			%li{class: "#{'active' if @type == 'best'}"}
				=link_to "Best", p(type:'best')
			%li{class: "#{'active' if @type == 'latest'}"}
				=link_to "Latest", p(type:'latest')

			

		

app/views/layouts/_show_image.html.haml
.row{id:'header-top-img-cont'}
	.col-md-12.overlay-header
		.row
			.col-md-10.col-md-offset-1
				%h1
					#intro-line.text-center
						Share
						&nbsp
						=fa_icon "hand-o-right", style: 'font-size:35px;'
						Vote
						&nbsp
						=fa_icon "hand-o-right", style: 'font-size:35px;'
						Discuss
				.margin-bottom-20

app/views/layouts/_sidebar.html.haml
.col-md-12
  %ul.list-group.sidebar-nav-v1{id:'main-nav'}

    %li.list-group-item{class: "#{'active' if @post_index}"}
      =link_to "All", root_path, class: 'tribe-links'
    
    -@tribes = Tribe.all
    -@tribes.each do |tr|
      %li.list-group-item{class: "#{'active' if @tribe && tr.name == @tribe.name}"}
        =link_to tr.name, tr,  class: 'tribe-links'
      

app/views/layouts/_st_index.html.haml
%nav.navbar{id: 'refine-nav'}
  .row{style:'margin-right:0px !important; margin-left:0px !important;'}  
    
    
    .col-md-5{id: "duration-header", style: 'padding-left:20px; padding-top:5px;'}
      %ul.nav.nav-pills.refine-top
        %li.refine-link{class: "#{'active' if !@duration_header }"}
          
          =link_to 'Hot', @st_tribe

        %li.refine-link{class: "#{'active' if @duration_header && !@new_header}"}
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#", "data-toggle"=>"dropdown", "data-hover"=>"dropdown", "data-delay"=>"30","data-close-others"=>"false"}
            Top
            =fa_icon "caret-down"
          %ul.dropdown-menu
            %li
              =link_to 'Today', top_sub_tribe_path(id: @st_tribe.id, duration: 'today')
            %li.divider
            %li
              =link_to 'This week',top_sub_tribe_path(id: @st_tribe.id, duration: 'week') 
            %li.divider
            %li
              =link_to 'This month',top_sub_tribe_path(id: @st_tribe.id, duration: 'month')
            %li.divider
            %li
              =link_to 'This year', top_sub_tribe_path(id: @st_tribe.id, duration: 'year') 
            %li.divider
            %li
              =link_to 'All time', top_sub_tribe_path(id: @st_tribe.id, duration: 'all_time') 
        %li.refine-link{class: "#{'active' if @new_header}"}
          =link_to 'Latest', new_sub_tribe_path(id: @st_tribe.id, duration: 'current') 

        %li
          =link_to (fa_icon "plus-circle", class: 'color-light-green', text: 'Submit a new link'), '#', id: 'submit-new-link-refine','data-toggle'=>"modal" ,'data-target'=>"#create-link-modal", style: 'display:none', class: 'btn btn-default'
    .col-md-7
      %ul.nav.navbar-nav         
        %li{id: 'username-refine', style: 'display:none;'}
          -if user_signed_in?
            .btn-group{style: 'cursor:pointer;'}
              #user-name-nav{"data-toggle" => "dropdown", href: "#", "data-toggle"=>"dropdown", "data-hover"=>"dropdown", "data-delay"=>"10","data-close-others"=>"false"}
                =fa_icon "user"
                =current_user.username
                =fa_icon "caret-down"
              %ul.dropdown-menu
                %li
                  =link_to 'My Account', current_user
                %li.divider
                %li
                  =link_to 'Sign out', destroy_user_session_path, method: 'delete'      
          -else
            =link_to('Login', new_user_session_path)
        
    

:javascript
  $(function(){
    var
      $createLink = $('#submit-new-link-refine'),
      $userLogin = $('#user-duration-header'),
      $brand = $('#brand-refine-bar'),
      $userName = $('#username-refine'),
      $tagLine = $('#tagline'),
      $win = $(window),

      $filter = $('#refine-nav'),
      $filterSpacer = $('<div />', {
        "class": "filter-drop-spacer",
        "height": $filter.outerHeight()
      });
    $win.scroll(function(){     
      if(!$filter.hasClass('navbar-fixed-top remove-grey-bck-nav') && $win.scrollTop() > $filter.offset().top){
        $filter.before($filterSpacer);
        $filter.addClass("navbar-fixed-top remove-grey-bck-nav");
        $tagLine.hide();
        $createLink.show();
        $brand.fadeIn();
        $userName.show();
        $userLogin.show();
        
      } else if ($filter.hasClass('navbar-fixed-top remove-grey-bck-nav')  && $win.scrollTop() < $filterSpacer.offset().top){
        $filter.removeClass("navbar-fixed-top remove-grey-bck-nav");
        $filterSpacer.remove();
        $createLink.hide();
        $userLogin.hide();
        $brand.fadeOut();
        $userName.hide();
        $tagLine.fadeIn();

      }
    });
  });

app/views/layouts/_trending_tribes.html.haml
#trending-tribes{style:'text-align:center; padding-left:15px; padding-right:15px; padding-top:10px; padding-bottom:10px;margin-right:15px;'}
	#intro-line
		Share, Vote and Discuss things that you relate with
	-ttrb= TrendingTribe.all
	-ttrb.each do |t|
		=link_to t.sub_tribe.name, t.sub_tribe, class: 'label label-warning'
		&nbsp	
	.pull-right{style:'padding-top:2px;'}
		%strong
			

app/views/layouts/_user_header.html.haml
%nav.navbar{role: "navigation", id: 'user-nav'}
	.row
		.col-md-5
		.col-md-6
			%ul.nav.navbar-nav
				%li.custom-center
					- if current_user == @user
						=link_to "My Account", @user, class: "tribe-nav-links #{'active' if current_page?(@user)}"
					-else
						=link_to "#{@user.username}", @user, class: "tribe-nav-links #{'active' if current_page?(@user)}"
				%li.custom-center
					- if current_user == @user
						=link_to "My Profile", edit_user_registration_path, class: "tribe-nav-links #{'active' if current_page?(edit_user_registration_path)}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Niblin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="Niblin" />
  <meta property="og:description" content="Niblin is a community where we share quality articles, news, videos and images from the web for people to view, vote and discuss" />
  <meta property="og:url" content="http://www.niblin.com/" />
  <meta property="og:image" content="http://www.niblin.com/assets/logo_150.png" />
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <link href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js">
  <link href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">

  <meta name="description" content="Niblin is a community where we share quality articles, news, videos and images from the web for people to view, vote and discuss">
  
  <% #<script src="http://js.pusher.com/2.0/pusher.min.js"></script> %>
  
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50235584-1', 'niblin.com');
  ga('send', 'pageview');
</script>


</head>
<body>
	<div class= 'container-fluid', id='main-container'> 
		<%= render 'layouts/header' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title>Niblin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "http://api.recaptcha.net/js/recaptcha_ajax.js" %>
  <%= stylesheet_link_tag    "/assets/jquery-mobile/jquery.mobile-1.4.2.min.css", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "/assets/jquery-mobile/jquery.mobile-1.4.2.min.js", "data-turbolinks-track" => false %>
  
  <%= stylesheet_link_tag    "/assets/mobile.css", media: "all", "data-turbolinks-track" => false %>
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="Niblin" />
  <meta property="og:description" content="Niblin is a community where we share our great finds on the web" />
  <meta property="og:url" content="http://www.niblin.com/" />
  <meta property="og:image" content="http://www.niblin.com/assets/logo_150.png" />
  
  <meta name="description" content="Niblin is a community where we share our great finds on the web">

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50235584-1', 'niblin.com');
  ga('send', 'pageview');
</script>
<script type="text/javascript">
  $(document).bind("mobileinit", function () {
    $.mobile.ajaxEnabled = false;
    $.mobile.linkBindingEnabled = false;
    $.mobile.hashListeningEnabled = false;
    $.mobile.pushStateEnabled = false;
  });
  
  $('div[data-role="page"]').live('pagehide', function (event, ui) {
    $(event.currentTarget).remove();
  });

</script>

</head>
<body>
  <%= yield %>
</body>

</html>